### ISSUE TITLE
appbar error

### ISSUE THREAD

**Issue by naiiu** [TechieBlossom/flightapp#1]
Compiler message:
lib/main.dart:25:15: Error: The argument type '#lib1::CustomAppBar' can't be assigned to the parameter type '#lib2::PreferredSizeWidget'.
Try changing the type of the parameter, or casting the argument to '#lib2::PreferredSizeWidget'.
      appBar: CustomAppBar(),
              ^
Compiler failed on C:\Users\shaoz\Downloads\flightapp-master\lib\main.dart
Gradle task assembleDebug failed with exit code 1

**Comment by pburel** [comment]
Could be:
      //appBar: CustomAppBar(),
      bottomNavigationBar: PreferredSize(
          preferredSize: Size.fromHeight(50.0), // here the desired height
          child: CustomAppBar(
            // ...
          ),
      ),

**Comment by TechieBlossom** [comment]
@pburel is right, but with a slight correction.
bottomNavigationBar: CustomAppBar().

in next code push, I will definitely update it.

**Comment by TechieBlossom** [comment]
@pburel is right, but with a slight correction.
bottomNavigationBar: CustomAppBar().

in next code push, I will definitely update it.
