### ISSUE TITLE
locations.clear();

### ISSUE THREAD

**Issue by pburel** [TechieBlossom/flightapp#2]
In main.dart you can add "locations.clear();"

addLocations(BuildContext context, List<DocumentSnapshot> snapshots) {
  **locations.clear();**
  for (int i = 0; i < snapshots.length; i++) {
    final Location location = Location.fromSnapshot(snapshots[i]);
    locations.add(location.name);
  }
}

**Comment by PrateekSharma1712** [comment]
Valid point, sure will take it.. and also will remove for loop and replace with something more appropriate like .map
