### ISSUE TITLE
Request: Branch without Firebase

### ISSUE THREAD

**Issue by JonasJW** [TechieBlossom/flightapp#3]
Hey,

I would love to have a branch that doesn't use Firebase. I would like to just explore the app without having to setup firebase! That would be great.

**Comment by Malthehave** [comment]
Hello. I was thinking the same thing. Did you have any luck finding one?

**Comment by JonasJW** [comment]
No, no update so far

**Comment by Malthehave** [comment]
Okay thanks for the update! If you find anyway around it, please give an update(:

**Comment by TechieBlossom** [comment]
Started today.. May be in a day or two, it will be done.. Its not hard but thinking on the best way to do that

**Comment by Malthehave** [comment]
> Started today.. May be in a day or two, it will be done.. Its not hard but thinking on the best way to do that

That's great!

**Comment by TechieBlossom** [comment]
Completed.. branch name only_ui.

Please provide feedback, if it is running. 
Don't hesitate to execute Flutter build clean if you already build master branch
