### ISSUE TITLE
Path Clip not working in android

### ISSUE THREAD

**Issue by Bunty07** [TechieBlossom/flightapp#4]
Hi
I tried to run the app
in android emulator  the path clip is not working properly.
Can you help me to fix this one
![screenshot_1546250234](https://user-images.githubusercontent.com/33190909/50558100-2356b180-0d11-11e9-9bd8-9ffd41dfc628.png)

**Comment by PrateekSharma1712** [comment]
Did u change some code? If yes, please post that code. Is this not running only on emulator?

**Comment by TechieBlossom** [comment]
Closing this issue.. Post the code if you find similar issue.
