### ISSUE TITLE
The argument type 'Center' can't be assigned to the parameter type (BuildContext, String) 

### ISSUE THREAD

**Issue by Nabiypy** [TechieBlossom/flightapp#5]
Hello Sir,
Kindly help me resolve this error message showing at main.dart line 467.
<img width="968" alt="screen shot 2019-02-28 at 4 56 21 pm" src="https://user-images.githubusercontent.com/6829713/53584062-b463d080-3b7a-11e9-930e-382665cfa4a4.png">

Error: The argument type '#lib1::Center' can't be assigned to the parameter type
'(#lib2::BuildContext, dart.core::String) → #lib2::Widget'.
Try changing the type of the parameter, or casting the argument to '(#lib2::BuildContext, dart.core::String) →
#lib2::Widget'.
                    placeholder: Center(child: CircularProgressIndicator()),
                                 ^
Compiler failed on /Users/hanson/VisualCodeProjects/flightapp/lib/main.dart
Error launching application on iPhone XR.

**Comment by PrateekSharma1712** [comment]
I think there is a version change for CachedNetworkImage. It worked when I used it earlier.

**Comment by Nabiypy** [comment]
> I think there is a version change for CachedNetworkImage. It worked when I used it earlier.

Please do we have to do a downgrade here ?
Advice.
Thank you

**Comment by PrateekSharma1712** [comment]
Yes. Might be.
Not sure. Earlier it used to take a widget and Center is a widget.
You can also try Align, to center the widget, if center is not working.

**Comment by jenicun** [comment]
yes it work earlier.. can someone post the fix ?

**Comment by wisonic** [comment]
`CachedNetworkImage(
        imageUrl: "http://via.placeholder.com/350x150",
        placeholder: (context, url) => new CircularProgressIndicator(),
        ...,
     )`

**Comment by jaasaria** [comment]
Im still receiving errors. Hope the author would update this project.

**Comment by PrateekSharma1712** [comment]
Tomorrow definitely. Check for pull tomorrow.
